### ISSUE TITLE
Meteor 1.9~ install fails due to compatibility issues with meteor-profiler

### ISSUE THREAD

**Issue by aogaili** [monti-apm/meteor-profiler#1]
It seems that profiler is not longer compatible with the upcoming Meteor 1.9 release. I think it has to do with the dependency on the [v8-Profiler](https://github.com/node-inspector/v8-profiler) package and the update to Node1 2.

I get the following error as soon as I attempt the update:

20 silly lifecycle v8-profiler@5.7.0~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
21 silly lifecycle v8-profiler@5.7.0~install: Returned: code: 1  signal: null
22 info lifecycle v8-profiler@5.7.0~install: Failed to exec install script
23 verbose stack Error: v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
23 verbose stack Exit status 1
23 verbose stack     at EventEmitter.<anonymous> (/Users/ali/.meteor/packages/meteor-tool/.1.9.0-alpha.2.uz1wg8.vwoi9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
23 verbose stack     at EventEmitter.emit (events.js:196:13)
23 verbose stack     at ChildProcess.<anonymous> (/Users/ali/.meteor/packages/meteor-tool/.1.9.0-alpha.2.uz1wg8.vwoi9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
23 verbose stack     at ChildProcess.emit (events.js:196:13)
23 verbose stack     at maybeClose (internal/child_process.js:1000:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
24 verbose pkgid v8-profiler@5.7.0
25 verbose cwd /Users/ali/.meteor/packages/montiapm_agent-binary-deps/.1.6.0.1fouv3d.n3py++os+web.browser+web.cordova/npm/node_modules/.temp-xypne1.88o6g
26 verbose Darwin 18.2.0
27 verbose argv "/Users/ali/.meteor/packages/meteor-tool/.1.9.0-alpha.2.uz1wg8.vwoi9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/ali/.meteor/packages/meteor-tool/.1.9.0-alpha.2.uz1wg8.vwoi9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
28 verbose node v12.1.0
29 verbose npm  v6.9.0
30 error code ELIFECYCLE
31 error errno 1
32 

32 error Exit status 1
33 error Failed at the v8-profiler@5.7.0 install script.
33 error This is probably not a problem with npm. There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by sebakerckhof** [comment]
There's [v8-profiler-next](https://www.npmjs.com/package/v8-profiler-next) which should support node 12.

**Comment by zodern** [comment]
I published version 1.5 today which supports Meteor 1.9.
