### ISSUE TITLE
[URGENT] CPU Profiling does not work

### ISSUE THREAD

**Issue by haunguyen90** [monti-apm/meteor-profiler#3]
I installed the package `meteor add montiapm:profiler` and having a paid account on montiapm, but I still don't see the CPU profiling?

Meteor version: 1.10.2

@zodern @arunoda Can one of you help me to resolve this issue, it's a bit urgent for me

<img width="1465" alt="Screen Shot 2021-02-18 at 16 32 17" src="https://user-images.githubusercontent.com/8245883/108336798-03dbb500-7207-11eb-9613-5ed77e98517f.png">

**Comment by zodern** [comment]
@haunguyen90 I've replied to your email.

**Comment by mibto** [comment]
@zodern Please reopen this issue, as i have exactly the same problem

**Comment by zodern** [comment]
@mibto to create a profile you click on `Take a Remote Profile`. It will give you instructions.

**Comment by mibto** [comment]
@zodern is there no continuous cpu profiling?

**Comment by zodern** [comment]
It is currently in a private beta. I will follow up to over email.

**Comment by bensquire** [comment]
@zodern Any chance of getting onboard the private beta?

**Comment by zodern** [comment]
@bensquire I just need the id's of the apps you want to use continuous profiling with (you can find it in the app's settings). You can send it to `hello@montiapm.com` or use the Support form in the top of https://app.montiapm.com.

**Comment by bensquire** [comment]
@zodern Thanks for the headsup, I've sent a message to the email listed.
